config/routes.rb
Rails.application.routes.draw do
  resources :listings

  get 'pages/flo'

  get 'pages/about'

  get 'pages/contact'

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	Paperclip.options[:command_path] = 'C:\Program Files\ImageMagick-6.8.9-Q16'
  	has_attached_file 					:image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "default.jpg",
  										:storage => :dropbox,
    									:dropbox_credentials => Rails.root.join("config/dropbox.yml")
  	validates_attachment_content_type 	:image, :content_type => /\Aimage\/.*\Z/
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Marketplace</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
       
      </ul>
     
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/listings/index.html.erb
<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
          
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency listing.price %></p>
            <%= link_to 'Show', listing, class: "btn btn-link" %>
            <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %>
            <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @listing.image.url %>
		</div>
	</div>
	<div class="col-md-6">
		<h3><%= @listing.name %></h3>
		<p><%= number_to_currency(@listing.price) %></p>
		<p><%= @listing.description %></p>

	</div>
</div>



<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>